name: Install

on: [ push, workflow_dispatch ]

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java_version: [ 11, 17 ]
        # https://github.com/actions/setup-java#supported-distributions
        java_distribution: [ temurin, zulu, liberica, microsoft, corretto, semeru ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK (${{ matrix.java_distribution }} ${{ matrix.java_version }})
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java_version }}
          distribution: ${{ matrix.java_distribution }}
      - name: Maven Install
        run: mvn --batch-mode install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
